Handle tukitd service problems
When tukitd service was not installed or not running, error
"TypeError: proxy.List is not a function" was displayed.

Better handling for such cases was added with more meaningful
messages.

Closes #7